name: flutter_core_logic
description: Core logic used in various apps and games.
version: 0.0.1
homepage: https://github.com/defuncart/flutter_core_logic

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^1.4.1+1
  flutter_tts: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: 1.2.1

flutter:
